### ISSUE TITLE
Icon centering (patch from Persona development theme)

### ISSUE THREAD

**Issue by tom-rade** [youhosi/nodebb-theme-oxide#10]
The issue mentioned here:
https://github.com/NodeBB/nodebb-theme-persona/issues/361

Is fixed by these commits:
https://github.com/Rabanov/nodebb-theme-persona/commit/8faa63afd87c4e07c5dab98ff15b5cf39d810698
https://github.com/Rabanov/nodebb-theme-persona/commit/0dfe8fde9df572e5f70e06804d851d4e3e06432f

So it shouldn't be too hard to implement those already.

**Comment by youhosi** [comment]
This is a very messy way to center the icons.
