### ISSUE TITLE
User status position on oxide-usercard

### ISSUE THREAD

**Issue by Eastrall** [youhosi/nodebb-theme-oxide#12]
I don't know if thats an issue or not, but I might have found a little css issue on the oxide-usercard: 

The online status is located on the top-right corner of the user card body in stead of being located after the user's name starting with an @ (eg. `@Eastrall`).
![image](https://user-images.githubusercontent.com/4021025/52372774-4899b680-2a59-11e9-8a3d-75f3feb7677e.png)
This is related to the general style applied by the `.status` that has the following properties:
```css
{
    position: absolute;
    top: 0;
    right: 0;
    vertical-align: 0;
}
```
Found in this file: https://github.com/youhosi/nodebb-theme-oxide/blob/8ddfac2da5f68a63b4ac00ca618d4359c7ed0723/less/topic.less#L150-L160

I've made some tests and found that if we remove the position, top and right properties, we would have the same behavior has the original nodebb theme. But, it would break the little status icon located near the avatar on the topic template:

![image](https://user-images.githubusercontent.com/4021025/52373301-a1b61a00-2a5a-11e9-80b1-b7a7f3e8f22a.png)

Another option would be to add a `.status` property to the `usercard.less` file so this style would be only applied to the card.

I can do a PR to fix that if you want. Just tell me which solution suits better the needs.

**Comment by youhosi** [comment]
@Eastrall the user's card will most likely look different, currently I do not have time to correct it. I will add that it will be like the one with a git B)

**Comment by Eastrall** [comment]
If you want I can make a PR and fix it. It will spare your time and focus on the new usercard.
