### ISSUE TITLE
Mobile visual does not looks well

### ISSUE THREAD

**Issue by jinfagang** [youhosi/nodebb-theme-oxide#16]
Hi, the theme on mobile shows abnormal, it swapable horizontal which is not good mobile users. Does it a bug or just in my case it show like this? I have test on both iOS and Android devices on chrome. All shows like this. **it would be better to make width same as screen width and can not swipe for mobile devices**

**Comment by youhosi** [comment]
@jinfagang It's set up specially, currently I do not have time to correct it because it would cause other problems.

**Comment by jinfagang** [comment]
@youhosi No warries, this theme seems so far so good :)
