### ISSUE TITLE
Small badge problem 

### ISSUE THREAD

**Issue by JeanBatiste73** [youhosi/nodebb-theme-oxide#18]
Hello,
When you put a group in invisible to prevent it from being seen in the list, the group's badge is not displayed on the profile
For example I'm in the admin group which is invisible but I'm looking to display the badge 

Thanks

**Comment by youhosi** [comment]
Use "show all badges in profile"

**Comment by JeanBatiste73** [comment]
Where is it?

**Comment by youhosi** [comment]
Look in Oxide Theme.

**Comment by JeanBatiste73** [comment]
The option is already activated

**Comment by youhosi** [comment]
In this case, NodeBB limits the display of the group after setting.

**Comment by JeanBatiste73** [comment]
So there's no way to display a badge even if the group is hidden ?

**Comment by youhosi** [comment]
@JeanBatiste73 If the group is set to "hidden" then it will not appear in either the group list or your profile. In order for someone to see it, you should deselect the option "Hidden".
