### ISSUE TITLE
Problem to assign a person during a report

### ISSUE THREAD

**Issue by JeanBatiste73** [youhosi/nodebb-theme-oxide#19]
Hello,
I don't understand why when I try to assign a person to the list there are lots of "Guest" and I don't see all my staff : https://www.useloom.com/share/fe6ca808f17c42acbe9d6959ab1faf4d

Thanks =)

**Comment by youhosi** [comment]
@JeanBatiste73 This is a NodeBB problem not a oxide style.

**Comment by JeanBatiste73** [comment]
Thanks it's fixed here : https://github.com/NodeBB/NodeBB/commit/0360f6e1cb39c1704dbec66e91351161d7787bde
