### ISSUE TITLE
[BUG] Duplicated sidebars / (popup) invalid data in profile

### ISSUE THREAD

**Issue by daffyyyy** [youhosi/nodebb-theme-oxide#23]
**Smartphone / Desktop:** Desktop
- **NodeBB version:** 1.12.2
- **NodeBB git hash:** 22db818eb40f04e528d95257c5517ded8341493d
 - **Device:** ------
 - **OS:** Windows 10
 - **Browser:** Brave

---

**Describe the bug**
All sidebars are duplicated, and on profile page when sidebars enabled jump popup "invalid data"
---

**Additional context / Screenshots**
http://prntscr.com/ov3m62
http://prntscr.com/ov3mnd
and one question is, how to add sidebars only on specific page e.g. like umod.pl?
No translate for 
pages:account/latest-posts, nick
No group badge in topic view

**Comment by youhosi** [comment]
U can give me a link to forum?

**Comment by daffyyyy** [comment]
https://forumek.pl

**Comment by youhosi** [comment]
Remove shoutbox plugin and check again.

**Comment by JeanBatiste73** [comment]
Same problem. I don't have a shoutbox plugin on the forum.

**Comment by daffyyyy** [comment]
> Remove shoutbox plugin and check again.

Without shoutbox too

**Comment by youhosi** [comment]
You must check if any of the plugins modifies the DOM elements of the page. From what I see is daffy you have a different structure of page elements.

@daffyyyy @JeanBatiste73 
Orginal:
<img width="650" alt="Zrzut ekranu 2019-09-2 o 17 28 27" src="https://user-images.githubusercontent.com/24297084/64124458-5d4bec00-cda7-11e9-8b73-62d9fd7353bc.png">

Yours: 
<img width="571" alt="Zrzut ekranu 2019-09-2 o 17 28 42" src="https://user-images.githubusercontent.com/24297084/64124473-63da6380-cda7-11e9-8ac5-22035c9f8b7a.png">

**Comment by youhosi** [comment]
@daffyyyy Also, you can see that for a split second when the page loads the style it looks normal.

**Comment by daffyyyy** [comment]
> @daffyyyy Also, you can see that for a split second when the page loads the style it looks normal.

Essentials extensions:
![Screenshot_49](https://user-images.githubusercontent.com/41084667/64128988-807f9700-cdb9-11e9-806b-5157d885d5bd.png)

![Screenshot_50](https://user-images.githubusercontent.com/41084667/64128994-92613a00-cdb9-11e9-8930-7a948dce2797.png)

Problem not resolved ;c

**Comment by youhosi** [comment]
You have a latest version on oxide and nodebb?

**Comment by JeanBatiste73** [comment]
For me yes ^^

**Comment by JeanBatiste73** [comment]
I've never had a problem, only since the update

**Comment by daffyyyy** [comment]
> You have a latest version on oxide and nodebb?

Yes,
![Screenshot_51](https://user-images.githubusercontent.com/41084667/64133678-61443200-cdd8-11e9-9530-3ec2a156156b.png)
![Screenshot_52](https://user-images.githubusercontent.com/41084667/64133704-85a00e80-cdd8-11e9-89d3-3c251e2dd34c.png)

**Comment by soulteary** [comment]
it's nodebb‘s fault

**Comment by youhosi** [comment]
Now, all its working fine
