### ISSUE TITLE
[BUG] Topic openning post weird UI on mobile

### ISSUE THREAD

**Issue by maciejbak85** [youhosi/nodebb-theme-oxide#24]
**Smartphone ( android )
- **NodeBB version: 1.31
- **NodeBB git hash: c6ef1486dee5cfb0d435716cf7d4d718fad68359
 - **Device:Xiaomi Redmi Note 8 Pro
 - **OS:Android 9.0 (Pie); MIUI 10
 - **Browser:Chrome

---

First post in the topic, has very weird UI. A lot of empty space.

---

**Additional context / Screenshots**
[https://ibb.co/3Ymsyvc](https://ibb.co/3Ymsyvc)

**Comment by maciejbak85** [comment]
![IMAGE 2019-12-13 21:49:05](https://user-images.githubusercontent.com/2299049/70834475-627ef500-1df2-11ea-9240-ef75d326e843.jpg)

**Comment by youhosi** [comment]
@maciejbak85  Every first post looks like this?

**Comment by maciejbak85** [comment]
Yes

śr., 1 sty 2020, 20:08 użytkownik Sebastian Sycz <notifications@github.com>
napisał:

**Comment by youhosi** [comment]
@maciejbak85 For me, the posts look normal, as well as on the phone, as well as on the laptop.

![IMG_5377](https://user-images.githubusercontent.com/24297084/71645127-b125fd80-2cd3-11ea-80c6-b0ddc8cd7c8a.PNG)

**Comment by maciejbak85** [comment]
yes now it looks ok, problem was before because ads where not ready yet, not displaying but leaving empty space there :)
