### ISSUE TITLE
No license is specified

### ISSUE THREAD

**Issue by oplik0** [youhosi/nodebb-theme-oxide#32]
This theme doesn't specify any code license, which means there are quite a few copyright problems possible here. To quote [choosealicense.com](https://choosealicense.com/no-permission/):

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

And the last part has already happened here: there are two other contributors to this project and any one is full copyright holder to his own contributions.

If the project is supposed to be as open as possible, I think the best license would be [MIT License](https://choosealicense.com/licenses/mit/). If you want to force all forks and code using this theme also being open source, [GPLv3](https://choosealicense.com/licenses/gpl-3.0/) is probably the best "viral" license.

**Comment by youhosi** [comment]
@oplik0 For security reasons I will add a MIT license.
