### ISSUE TITLE
Dark Theme mode always turned on

### ISSUE THREAD

**Issue by maciejbak85** [youhosi/nodebb-theme-oxide#34]
**Smartphone / Desktop:** (please complete the following information)
- **NodeBB version:1.13.2
 - **Device: all different
 - **OS:  all different
 - **Browser:  all different
---

with current version of theme ( with default dark theme off in admin panel ), every user has it on, and when they switch it off, after page refresh it goes back to dark.

**Comment by youhosi** [comment]
@maciejbak85 Okey, now all its work perfect! 

U can install:

`npm install nodebb-theme-oxide@latest`

or 

`npm install nodebb-theme-oxide@5.0.42`

**Comment by maciejbak85** [comment]
ok works good thanks!
