### ISSUE TITLE
Sidebar is over footer ( at the bottom )

### ISSUE THREAD

**Issue by maciejbak85** [youhosi/nodebb-theme-oxide#35]
**Smartphone / Desktop:** (please complete the following information)
- **NodeBB version:1.13.2
- **Device: all different
- **OS: all different
- **Browser: all different

---

Looks like after update sidebar widgets are just over the footer, the bottom not at the right side.
---

**Additional context / Screenshots**

[https://imgur.com/a/ZDMql9P](https://imgur.com/a/ZDMql9P)

**Comment by youhosi** [comment]
@maciejbak85 Hello, for tablets and smartphones, the sidebar is moved to the bottom of the page. This is the intended effect.

**Comment by maciejbak85** [comment]
heh but the screen is from mac osx :)

**Comment by maciejbak85** [comment]
heh but the screen is from mac osx :)

**Comment by youhosi** [comment]
@maciejbak85 The appearance of the page depends on the resolution, not the type of device.
