### ISSUE TITLE
[BUG] Navigation Links + Search Bar.

### ISSUE THREAD

**Issue by MotherShip808** [youhosi/nodebb-theme-oxide#36]
**Desktop:** (please complete the following information)
- **NodeBB version: Latest 1.3.x**
- **NodeBB git hash: ?** (git rev-parse HEAD)
 - **Device: Chrome**
 - **OS: Windows 10**
 - **Browser:**

---

**Describe the bug**
When you add extra Links to the Navigation Plane, it pushes the whole Navigation bar to under the logo/forum name. This wouldnt be an issue except the header itself isnt set to extend, so the header hides the forum navigation as well as the top of custom pages.

I also noticed this on the default set of navigation icons, except it only drops down when you go to a forum thread, and the comment navigation is added to the top header as well.

---

**Additional context / Screenshots**
https://i.imgur.com/CyrHKaC.png
https://i.imgur.com/WZNMtdT.png

**Comment by youhosi** [comment]
@MotherShip808 Fixed! Changes will appear in the new release along with other patches :smiley:

**Comment by MotherShip808** [comment]
I am still running into the bug with the nav bar overlapping with the main index container hiding the forum path, and annoucements. I was able to fix this by adding style="padding-top:50px;" to the container in templates/header.tpl

https://i.imgur.com/SEKamny.png

This isnt a perfect solution, but it works for my forum since our nav bar is big enough to warrant this .
