### ISSUE TITLE
Steam SSO Intergration Question

### ISSUE THREAD

**Issue by MotherShip808** [youhosi/nodebb-theme-oxide#38]
Hello!

So I had a question that perhaps you would be knowledgeable enough to be able to assist me with. I have a Steam SSO plugin that allows user to login/register via steam, and it saves their steam profile and steam64 ID to their user info in the mongodb, however it does not display that information on their profiles, as the plugin wasn't made to be able to do that, however for the project I am working on, making that information publicly accessible, as well as make a script that can take their steam64 ID and apply it to additional user links. For TF2, most websites use their 64id as their profile link. so things like rgl.gg/user/steam64. I was wondering if you might know how do this, or at the least, what I would need to edit/do on your theme to be able to display that information.

Thanks, and I appreciate the help!

**Comment by youhosi** [comment]
@MotherShip808 At the beginning you would have to add route to the topic using hooks and set the parameter `:steamID`, then download steamID64 from mongoDB and the rest of the user data, if the user is found, just redirect you to the appropriate profile. It's basically, unfortunately, I don't have enough time to go deeper into this topic.

I think @barisusakli  would help you more 😛

**Comment by MotherShip808** [comment]
If it helps, I am using this plugin that I had to jerry rig with the help of another to get functional
https://github.com/MotherShip808/nodebb-plugin-sso-steam-v2/blob/master/library.js

`// Add some APIs for themes to use
	Steam.addPostUserData = function (data, callback) {
		Steam.getSteamidByUid(data.uid, function (err, steamid) {
			if ((err == null) && (steamid !== null)) {
				data['steam-sso:steamid'] = steamid;
				data['steam-sso:profile'] = profileurl(steamid);
			}
			callback(null, data);
		})
	}
`
so it should be easier than trying to make it work from scratch, however I have idea what any of this means.
