### ISSUE TITLE
Second row on subcategories

### ISSUE THREAD

**Issue by tom-rade** [youhosi/nodebb-theme-oxide#5]
When you have a lot of subcategories, there should be a new line, instead of a scrollbar. This is currently used in persona and is way more practical. Would also appreciate CSS-snippet to change this if this won't be changed in master.

**Comment by youhosi** [comment]
@tom-rade Could you give a screenshot?

**Comment by tom-rade** [comment]
https://imgur.com/Eds7duu There you go

**Comment by youhosi** [comment]
Hello @tom-rade! I will not change this to branch master, but you have here the code that corrects it, let me know if exactly what you wanted! :)

```sass
[component="categories/category"] {
    .category-children {
        display: block !important;
        flex-wrap: unset !important;
        padding-bottom: 5px !important;
        
        .category-children-item {
            width: ~"calc(33% - 10px)";
            padding-bottom: 10px;
            display: block;
            flex: unset;
        }
    }
}
```

**Comment by tom-rade** [comment]
@youhosi Doesn't look very nice but still thanks. Could you nullify your changes for .category-children and .category-children-item (I think) and just use the persona way of doing things? Persona just does lists them in display: block; without doing seperated 33% width like this code.

**Comment by youhosi** [comment]
@tom-rade, sure:

```sass
[component="categories/category"] {
    .category-children {
        display: block !important;
        flex-wrap: unset !important;
        padding-bottom: 5px !important;
        
        .category-children-item {
            width: ~"calc(33% - 10px)";
            padding-bottom: 10px;
            display: block;
            flex: unset;
        }
    }
}
```

**Comment by tom-rade** [comment]
@youhosi I eventually settled for this custom CSS (easier to implement and is consistent across theme updates:

```
.category-children {
    display: block !important;
    flex-wrap: unset !important;
    padding-bottom: 5px !important;
}
.category-children-item {
    padding-bottom: 5px;
    display: block;
    flex: unset;
}

Thank you
```
