### ISSUE TITLE
(Option to) show all badges on the post and profile by default

### ISSUE THREAD

**Issue by tom-rade** [youhosi/nodebb-theme-oxide#8]
According to this issue, the displaying of all badges next to posts and on the profile is possible:

https://github.com/NodeBB/NodeBB/issues/7180
"Display of badges is controlled at the theme level, themes can elect to show all badges, as the data is (or should be, anyway) available for use in templates."

So technically, it should be possible to implement it that way. I'd very much appreciate it and this is the only thing needed for us to switch to this theme.

**Comment by youhosi** [comment]
@tom-rade Adding a few badges can cause the style to be displayed badly on mobile devices.
But adding them to the user profile would not be a major problem.

**Comment by tom-rade** [comment]
@youhosi I understand, but add the option in the settings please. On my forum, most people have 2-3 groups which wouldn't cause style issues. And I can't go into each of the 500 users and select badges.

**Comment by youhosi** [comment]
@tom-rade Style allows you to set multiple tags, most likely you did not do it in the group settings (allow multiple bagdes)

**Comment by tom-rade** [comment]
@youhosi Yes I know, I set multiple badges. But as a user, I have to select MANUALLY which badges are shown - but I want all badges to be shown.

**Comment by youhosi** [comment]
@tom-rade Only where I can display all groups is the profile view.

**Comment by tom-rade** [comment]
@youhosi Are you sure about that? Cause theoretically you just copy the template from the group list in profile to the posts. And then edit the style.

**Comment by youhosi** [comment]
@tom-rade Yes, or I do not know / saw a function that could do it, unfortunately NodeBB has a lot of limits for themes.

**Comment by youhosi** [comment]
this:

```tpl
				<!-- BEGIN groups -->
				<a href="{config.relative_path}/groups/{groups.slug}">
					<span class="label group-label inline-block" style="background-color: {groups.labelColor};">
						<!-- IF groups.icon --><i class="fa {groups.icon}"></i> <!-- ENDIF groups.icon -->{groups.userTitle}
					</span>
				</a>
				<!-- END groups -->
```
It will no longer work in the posts view.

**Comment by tom-rade** [comment]
@youhosi Hmm interesting. Ok thanks anyways.
