### ISSUE TITLE
Change color of light gray description and other small texts

### ISSUE THREAD

**Issue by tom-rade** [youhosi/nodebb-theme-oxide#9]
The only other thing bothering me, is the colors of descriptions and small texts. For example:

```
[component="category"] .category-details .content .show-separator .description {
    font-size: 12px;
    color: #bbb;
}
```

`#bbb` is way too light on most displays causing the user to barely read anything. Some other CSS classes where it's too light: .categories-title .breadcrumb .categories .category-details

**Comment by youhosi** [comment]
@tom-rade In which case, what color would be appropriate in your opinion?

**Comment by tom-rade** [comment]
@youhosi Something like #303030

**Comment by youhosi** [comment]
@tom-rade `#303030` and `#444444` is too dark and would stand out too much in the template.

**Comment by tom-rade** [comment]
@youhosi Hmm yeah, the theme is indeed pretty light. But most #bbb classes should be changed so it gets normalized. Otherwise I'd try using #7c7c7c, that would still be more readable than #bbb. But #bbb is way too light and unreadable.

**Comment by youhosi** [comment]
@tom-rade To set a darker color in these classes, the whole style would have to be adapted from the beginning.

```less
@gray-base:              #444444;
@gray-darker:            lighten(@gray-base, 13.5%); // #666
@gray-dark:              lighten(@gray-base, 20%); // #777
@gray:                   lighten(@gray-base, 33.5%); // #999
@gray-light:             lighten(@gray-base, 37%); // lighten(@gray-base, 46.7%); // #bbbbbb
@gray-lighter:           lighten(@gray-base, 65%); // #eaeaea
```

**Comment by tom-rade** [comment]
@youhosi Yep, but I find it is necessary. #bbb is waaaay too light. Text should be black (even here on GitHub, on a light theme - it's black) - not gray.

**Comment by youhosi** [comment]
@tom-rade All in all a fact, so you will need to work on the color style. Do you have any suggestions regarding colors? Take into account that they also can not stand out too much from the rest of the elements.
